appName-web-app/src/main/java/com/web/bean/MbCountry.java
package com.web.bean;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import com.web.bean.data.DataGenerator;

@ManagedBean(name = "mbCountry")
@ViewScoped
public class MbCountry implements Serializable {

    private Country selectedCountry;
    private City selectedCity;

    public List<Country> getCountries() {
        return DataGenerator.generateCountries();
    }

    public List<City> getCitites(Country country) {
        System.out.println("get String : " + country);
        if (country != null) {
            return country.getCities();
        }
        return null;
    }

    public Country getSelectedCountry() {
        return selectedCountry;
    }

    public void setSelectedCountry(Country selectedCountry) {
        this.selectedCountry = selectedCountry;
    }

    public City getSelectedCity() {
        return selectedCity;
    }

    public void setSelectedCity(City selectedCity) {
        this.selectedCity = selectedCity;
    }

}

appName-web-app/src/main/webapp/lov/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pe="http://primefaces.org/ui/extensions"
	template="../template/common/commonLayout.xhtml">
	<ui:define name="content">

		<h:form id="form">

			<p:panelGrid columns="3" style="width:100%;">
				<p:outputLabel value="Country" />
				<p:inputText id="selectedCountry"
					value="#{mbLov.selectedCountry.name}" />
				<p:commandButton value="Select Country" onclick="PF('dlg').show();"
					type="button" icon="ui-icon-extlink" update=":form:dlg" />

				<p:outputLabel value="City" />
				<p:inputText id="selectedCityInput"
					value="#{mbLov.selectedCity.name}" />
				<p:commandButton value="Select City" onclick="PF('dlgCity').show();"
					type="button" icon="ui-icon-extlink" update=":form:dlgCity" />
			</p:panelGrid>

			<p:dialog header="Countries" widgetVar="dlg" closeOnEscape="true"
				closable="false" width="40%" dynamic="true">

				<p:ajax event="close" listener="#{mbLov.handleClose}" />
				<p:ajax event="move" listener="#{mbLov.handleMove}" />

				<p:dataTable id="eventsDT" var="country"
					value="#{mbCountry.countries}" selectionMode="single"
					selection="#{mbCountry.selectedCountry}" rowKey="#{country.id}">
					<f:facet name="header">Select Country</f:facet>
					<p:ajax event="rowSelect" listener="#{mbLov.onRowSelect}"
						update="@form" />
					<p:ajax event="rowUnselect" listener="#{mbLov.onRowUnselect}"
						update=":form:selectedCountry" />
					<p:column headerText="Name">
						<h:outputText value="#{country.name}" />
					</p:column>
				</p:dataTable>
			</p:dialog>

			<p:dialog header="Cities" widgetVar="dlgCity" dynamic="false">
				<h:panelGrid columns="1" cellpadding="1">
#{mbCountry.selectedCountry}
					<p:dataTable id="eventsDTCity" var="city"
						value="#{mbCountry.getCitites(mbCountry.selectedCountry)}"
						selectionMode="single" selection="#{mbCountry.selectedCity}"
						rowKey="#{city.id}">
						<f:facet name="header">Select City from #{mbLov.selectedCountry.name}</f:facet>
						<p:ajax event="rowSelect" listener="#{mbLov.onCityRowSelect}"
							update="@form" />
						<p:column headerText="Name">
							<h:outputText value="#{city.name}" />
						</p:column>
					</p:dataTable>
				</h:panelGrid>
			</p:dialog>


		</h:form>

	</ui:define>
</ui:composition>