secutiry-model/src/main/java/security/main/AbstractManagedBean.java
package security.main;

import java.lang.annotation.Annotation;

import javax.faces.bean.ManagedProperty;

import security.anno.SecuredManagedBean;
import security.bean.SecurityOperation;
import security.provider.SecurityRolesProvider;
import security.test.SecurityRolesProviderMock;
import app.web.vo.LoginUserVO;

public abstract class AbstractManagedBean {

    @ManagedProperty(value = "#{loginUserVO}")
    private LoginUserVO loginUserVO;

    public LoginUserVO getLoginUserVO() {
        if (loginUserVO == null) {
            loginUserVO = new LoginUserVO();
            loginUserVO.setText("init");
        }
        return loginUserVO;
    }

    public void setLoginUserVO(LoginUserVO loginUserVO) {
        this.loginUserVO = loginUserVO;
    }

    protected abstract Class<?> getServiceBean();

    private SecurityRolesProvider getSecurityProvider() {
        return SecurityRolesProviderMock.getInstance();
    }

    public boolean isAllowed(String operation) {
        if (getServiceBean().isAnnotationPresent(SecuredManagedBean.class)) {
            Annotation annotation = getServiceBean().getAnnotation(SecuredManagedBean.class);
            SecuredManagedBean sec = (SecuredManagedBean) annotation;
            security.bean.SecurityClass classVO = getSecurityProvider().findByName(sec.name());
            if (classVO == null) {
                return true;
            }

            SecurityOperation op = classVO.findAllowedOperation(operation);

            if (op != null) {
                return op.isUserAuthorized(getLoginUserVO());
                // return
                // op.getAllowedRoles().contains(getUserBean().getRoles());
            }

            return false;
        } else {
            return true;
        }
    }

    public boolean isViewEnabled() {
        return isAllowed("VIEW");
    }

    public boolean isAddEnabled() {
        return isAllowed("ADD");
    }

    public boolean isEditEnabled() {
        return isAllowed("EDIT");
    }

    public boolean isDeleteEnabled() {
        return isAllowed("DELETE");
    }

    public boolean isPrintEnabled() {
        return isAllowed("PRINT");
    }

    public boolean isExecuteEnabled() {
        return isAllowed("EXECUTE");
    }
}

secutiry-model/src/main/webapp/admin/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pe="http://primefaces.org/ui/extensions"
	template="../template/common/commonLayout.xhtml">
	<ui:define name="content">

		<h:form id="form1">
		<p:outputLabel value="Welcome to ADMIN page" />
			<p:panelGrid columns="2" styleClass="login-panel">
				<p:outputLabel value="User Name" />
				<p:outputLabel value="#{loginUserVO.userName}" />
			</p:panelGrid>
			<p:panel>
				<p:dataTable var="row" value="#{loginUserVO.roles}">
					<p:column>
						<f:facet name="header">User's Roles</f:facet>
						<p:outputLabel value="#{row}" />
					</p:column>
				</p:dataTable>
				<p:commandButton action="#{mbLogin.logoutAction}" value="Logout" />
			</p:panel>

			<p:panel>
				<p:commandButton disabled="#{!mbAdminHome.viewEnabled}" value="View" />
				<p:commandButton disabled="#{!mbAdminHome.addEnabled}" value="Add" />
				<p:commandButton disabled="#{!mbAdminHome.editEnabled}" value="Edit" />
				<p:commandButton disabled="#{!mbAdminHome.deleteEnabled}" value="Delete" />
				<p:commandButton disabled="#{!mbAdminHome.executeEnabled}" value="Execute" />
				<p:commandButton disabled="#{!mbAdminHome.printEnabled}" value="Print" />

			</p:panel>

		</h:form>
	</ui:define>
</ui:composition>